spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: 
        username: 
        password: 
oauth:
    apiKey: 
    clientId: 
    clientSecret: 
    redirectURI: http://localhost:8080/login/oauth2/code/google
    scope: https://www.googleapis.com/auth/youtube.force-ssl


