spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://root:db2C1-GaA2HFhE5A3d6H4Gh16H6FFGb6@roundhouse.proxy.rlwy.net:41011/railway
        username: root
        password: db2C1-GaA2HFhE5A3d6H4Gh16H6FFGb6


